# Generated by Django 3.2.6 on 2021-08-12 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='card_number',
        ),
    ]
