# Generated by Django 3.2.6 on 2021-08-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_remove_test_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='card_number',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
